from pyspark.sql.types import StructType, StructField, IntegerType, StringType, BooleanType

sf_fire_service_calls = StructType([StructField('CallNumber', IntegerType(), True),
                                    StructField('UnitId', StringType(), True),
                                    StructField('IncidentNumber', IntegerType(), True),
                                    StructField('CallType', StringType(), True),
                                    StructField('CallDate', StringType(), True),
                                    StructField('WatchDate', StringType(), True),
                                    StructField('ReceivedDtTm', StringType(), True),
                                    StructField('EntryDtTm', StringType(), True),
                                    StructField('DispatchDtTm', StringType(), True),
                                    StructField('ResponseDtTm', StringType(), True),
                                    StructField('OnSceneDtTm', StringType(), True),
                                    StructField('TransportDtTm', StringType(), True),
                                    StructField('HospitalDtTm', StringType(), True),
                                    StructField('CallFinalDisposition', StringType(), True),
                                    StructField('AvailableDtTm', StringType(), True),
                                    StructField('Address', StringType(), True),
                                    StructField('City', StringType(), True),
                                    StructField('ZipCode', IntegerType(), True),
                                    StructField('Battalion', StringType(), True),
                                    StructField('StationArea', StringType(), True),
                                    StructField('Box', IntegerType(), True),
                                    StructField('OriginalPriority', IntegerType(), True),
                                    StructField('Priority', IntegerType(), True),
                                    StructField('FinalPriority', IntegerType(), True),
                                    StructField('ALSUnit', BooleanType(), True),
                                    StructField('CallTypeGroup', StringType(), True),
                                    StructField('NumberOfAlarms', IntegerType(), True),
                                    StructField('UnitType', StringType(), True),
                                    StructField('UnitSequenceInCallDispatch', IntegerType(), True),
                                    StructField('FirePreventionDistrict', IntegerType(), True),
                                    StructField('SupervisorDistrict', IntegerType(), True),
                                    StructField('NeighborhoodsAnalysisBoundaries', StringType(), True),
                                    StructField('RowId', StringType(), True),
                                    StructField('CaseLocation', StringType(), True),
                                    StructField('DataAsOf', StringType(), True),
                                    StructField('DataLoadedAt', StringType(), True),
                                    StructField('Analysis Neighborhoods', IntegerType(), True)])
